### PR TITLE
Feature/payment gateway

### PR DESCRIPTION
**Pull request by Xaroz**
- Added a button in profile that opens a new page to add payment card info
- Added payment card info that displays a card that changes depending on the number input, it uses the following library: https://github.com/amarofashion/react-credit-cards
- Added validation to all fields (prob need more work)

### CODE REVIEW

**Comment by Evalir** [comment]
Will check ltr @Xaroz , can you post some screenshots?

**Comment by Xaroz** [comment]
[https://gyazo.com/8a9644a695d56fa24e99c1a73f266f84](url)

**Comment by Evalir** [comment]
Looking sick af!

**Pull request closed without merging**
